# on: push
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     if: github.ref != 'refs/heads/main'
#     steps:
#       - name: 'checkout'
#         uses: actions/checkout@v2
#       - name: 'build'
#         uses: shalzz/zola-deploy-action@v0.13.0
#         env:
#           PAGES_BRANCH: gh-pages
#           BUILD_DIR: .
#           TOKEN: ${{ secrets.TOKEN }}
#           BUILD_ONLY: true
#   build_and_deploy:
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main'
#     steps:
#       - name: 'checkout'
#         uses: actions/checkout@v2
#       - name: 'build and deploy'
#         uses: shalzz/zola-deploy-action@v0.13.0
#         env:
#           PAGES_BRANCH: gh-pages
#           BUILD_DIR: .
#           TOKEN: ${{ secrets.PUBLIC_TOKEN }}
#           REPOSITORY: GITHUB_REPOSITORY

# name: Build website

# on: push
#   # push:
#   #   branches:
#   #     - source
#   # pull_request:
#   #   branches:
#   #     - source

# jobs:
#   build:
#     # we use mac because zola is not distributed in ubuntu (?)
#     # and I did not want to cargo build zola as part of the workflow
#     runs-on: macos-10.15
#     if: github.ref == 'refs/heads/main'
#     env:
#       TARGET_BRANCH: main
#     steps:
#     - name: Check out repo
#       uses: actions/checkout@v2
#     - name: Install zola
#       run: brew install zola
# #    - name: Get theme
# #      run: git submodule add https://github.com/RatanShreshtha/DeepThought.git themes/DeepThought 
#     - name: Generate HTML
#       run: zola build
#     - name: Commit and push to target branch
#       run: |-
#         git config --global user.email "workflow-bot@example.com"
#         git config --global user.name "workflow-bot"
#         git checkout --orphan $TARGET_BRANCH
#         git rm --cached -r .
#         mv public ..
#         rm -rf *
#         mv ../public/* .
#         touch .nojekyll
#         git add .
#         git commit -m "generated using zola build"
#         git push --set-upstream origin $TARGET_BRANCH --force


#https://github.com/svavs/codinfox-zola/blob/master/.github/workflows/build-action.yaml
name: Zola Deploy to Pages on push
on: push

jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: 'Build and deploy'
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          BUILD_FLAGS: --drafts
          TOKEN: ${{ secrets.BUILD }}